/* tslint:disable */
/* eslint-disable */
/**
 * Recipe Management API
 * レシピ管理API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {Array<ErrorResponseErrorsInner>}
     * @memberof ErrorResponse
     */
    'errors': Array<ErrorResponseErrorsInner>;
}
/**
 * 
 * @export
 * @interface ErrorResponseErrorsInner
 */
export interface ErrorResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseErrorsInner
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseErrorsInner
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Recipe
 */
export interface Recipe {
    /**
     * 
     * @type {number}
     * @memberof Recipe
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'updated_at': string;
}
/**
 * 
 * @export
 * @interface RecipeCreateRequest
 */
export interface RecipeCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof RecipeCreateRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreateRequest
     */
    'description'?: string | null;
}
/**
 * 
 * @export
 * @interface RecipeUpdateRequest
 */
export interface RecipeUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdateRequest
     */
    'description'?: string | null;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary レシピ作成
         * @param {RecipeCreateRequest} recipeCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecipe: async (recipeCreateRequest: RecipeCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recipeCreateRequest' is not null or undefined
            assertParamExists('createRecipe', 'recipeCreateRequest', recipeCreateRequest)
            const localVarPath = `/recipes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recipeCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary レシピ削除
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRecipe: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRecipe', 'id', id)
            const localVarPath = `/recipes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary レシピ詳細取得
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecipe: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRecipe', 'id', id)
            const localVarPath = `/recipes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary レシピ一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRecipes: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/recipes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary レシピ更新
         * @param {number} id レシピID
         * @param {RecipeUpdateRequest} recipeUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRecipe: async (id: number, recipeUpdateRequest: RecipeUpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRecipe', 'id', id)
            // verify required parameter 'recipeUpdateRequest' is not null or undefined
            assertParamExists('updateRecipe', 'recipeUpdateRequest', recipeUpdateRequest)
            const localVarPath = `/recipes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recipeUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary レシピ作成
         * @param {RecipeCreateRequest} recipeCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRecipe(recipeCreateRequest: RecipeCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Recipe>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRecipe(recipeCreateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary レシピ削除
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRecipe(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRecipe(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary レシピ詳細取得
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecipe(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Recipe>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecipe(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary レシピ一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRecipes(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Recipe>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRecipes(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary レシピ更新
         * @param {number} id レシピID
         * @param {RecipeUpdateRequest} recipeUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRecipe(id: number, recipeUpdateRequest: RecipeUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Recipe>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRecipe(id, recipeUpdateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary レシピ作成
         * @param {RecipeCreateRequest} recipeCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecipe(recipeCreateRequest: RecipeCreateRequest, options?: any): AxiosPromise<Recipe> {
            return localVarFp.createRecipe(recipeCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary レシピ削除
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRecipe(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteRecipe(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary レシピ詳細取得
         * @param {number} id レシピID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecipe(id: number, options?: any): AxiosPromise<Recipe> {
            return localVarFp.getRecipe(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary レシピ一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRecipes(options?: any): AxiosPromise<Array<Recipe>> {
            return localVarFp.listRecipes(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary レシピ更新
         * @param {number} id レシピID
         * @param {RecipeUpdateRequest} recipeUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRecipe(id: number, recipeUpdateRequest: RecipeUpdateRequest, options?: any): AxiosPromise<Recipe> {
            return localVarFp.updateRecipe(id, recipeUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary レシピ作成
     * @param {RecipeCreateRequest} recipeCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createRecipe(recipeCreateRequest: RecipeCreateRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createRecipe(recipeCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary レシピ削除
     * @param {number} id レシピID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteRecipe(id: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteRecipe(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary レシピ詳細取得
     * @param {number} id レシピID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRecipe(id: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRecipe(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary レシピ一覧取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listRecipes(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listRecipes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary レシピ更新
     * @param {number} id レシピID
     * @param {RecipeUpdateRequest} recipeUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateRecipe(id: number, recipeUpdateRequest: RecipeUpdateRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateRecipe(id, recipeUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


